"""add user_id column into article table

Revision ID: 022c23dc903c
Revises: 253a1793f32c
Create Date: 2021-03-08 01:26:00.252630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022c23dc903c'
down_revision = '253a1793f32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'user_id')
    # ### end Alembic commands ###
