"""create articles and tags and article_tag table

Revision ID: 253a1793f32c
Revises: 399bb81f43dd
Create Date: 2021-03-05 02:17:36.052673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253a1793f32c'
down_revision = '399bb81f43dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('article_id', 'tag')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('contents', sa.TEXT(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tag'),
    sa.UniqueConstraint('tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('articles')
    op.drop_table('article_tag')
    # ### end Alembic commands ###
